name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.12.0
      uses: actions/setup-node@v2
      with:
        node-version: 20.12.0
    - run: |
        cd ./dinner-ideas
        npm ci
        npm run build --if-present
        cd ./build

    - run: echo syncing build files to S3
    - run: aws s3 sync . s3://shaun-web-app-bucket
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'
