name: Front End & Back End Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  front-end-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Use Node.js 20.12.0
      uses: actions/setup-node@main
      with:
        node-version: 20.12.0
    - run: |
        cd ./dinner-ideas
        npm ci
        npm run build
      env:
        VITE_APP_API_ENDPOINT: ${{ secrets.API_ENDPOINT }}

    - run: echo syncing build files to S3
    - run: |
        cd ./dinner-ideas/build
        aws s3 sync . s3://shaun-web-app-bucket --acl public-read
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'

  back-end-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Use .NET 8
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 8.x
    - run: |
        cd ./dinner-ideas-api
        ./zip.sh
        ./update-lambda.sh
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-west-1'

